name: Bump Version

on:
  push:
    branches: [ master ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - run: cat ./package.json
      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@v9.0.39
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cat ./package.json
